=encoding_utf8

=head1 AutoOp tool

=head2 DESCRIPTION

This is yet another auto op tool... allows to add, delete and list autoop users.

=head2 SYNOPSIS

 irssi commands:

    /autoop_help
    /autoop_list
    /autoop_add
    /autoop_del
    /autoop_set

=head2 Op everyone in specific channel

    /autoop_add op_everyone
    /autoop_set op_everyone channels #this_channel
    /autoop_set op_everyone hostnames *@*
    /autoop_set alternatives *


